---
# tasks file for Elasticsearch

- name: Install Prerequisite of ELK
  apt:
    name: 
      - nginx
      - openjdk-8-jdk
    state: present
    update_cache: yes
    
### Installing Elasticsearch
- name: Import the Elasticsearch public GPG key into APT
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add the Elastic source list to the sources.list.d directory
  copy:
    content: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
    dest: /etc/apt/sources.list.d/elastic-7.x.list

- name: Install elasticsearch
  apt:
    name: elasticsearch
    state: present
    update_cache: yes


- name: Replace localhost in elasticsearch.yml
  replace:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '.network.host(.*)$'
    replace: 'network.host: localhost'
    
- name: Start Elasticsearch Service
  systemd:
    state: started
    name: elasticsearch
    enabled: yes
  ignore_errors: yes
  

